### ISSUE TITLE
Mask RCNN save the best segm model

### ISSUE THREAD

**Issue by pu2is** [hyz-xmaster/swa_object_detection#10]
Hi,
really glad that the save_the_best_model is updated. But would like to ask, how can i save the best_segm_mAP.pth, but not best_bbox_mAP.pth?
thx:)

**Comment by hyz-xmaster** [comment]
Hi,

 To enable saving the best_segm_mAP.pth, basically,  I think you need to make following changes:

[`swa_load_from = 'best_bbox_mAP.pth'`](https://github.com/hyz-xmaster/swa_object_detection/blob/2feb86790a41f91c3167fb282ba47dc295c65658/configs/_base_/swa.py#L9) -> `swa_load_from = 'best_segm_mAP.pth'`

[`if cfg.swa_load_from == 'best_bbox_mAP.pth':`](https://github.com/hyz-xmaster/swa_object_detection/blob/2feb86790a41f91c3167fb282ba47dc295c65658/mmdet/apis/train.py#L269) ->
`if cfg.swa_load_from == 'best_bbox_mAP.pth' or cfg.swa_load_from == 'best_segm_mAP.pth':`

[`eval_hook(val_dataloader, save_best='bbox_mAP', **eval_cfg))`](https://github.com/hyz-xmaster/swa_object_detection/blob/2feb86790a41f91c3167fb282ba47dc295c65658/mmdet/apis/train.py#L155) -> `eval_hook(val_dataloader, save_best='segm_mAP', **eval_cfg))`

[`val_dataloader, save_best='bbox_mAP', **eval_cfg)`](https://github.com/hyz-xmaster/swa_object_detection/blob/2feb86790a41f91c3167fb282ba47dc295c65658/mmdet/apis/train.py#L239) -> `val_dataloader, save_best='segm_mAP', **eval_cfg)`

**Comment by pu2is** [comment]
Yess, it works. Thanks again!

**Comment by pu2is** [comment]
Sorry but i would like to ask again, if swa support the cascade mask rcnn, ms rcnn or htc?

**Comment by hyz-xmaster** [comment]
Hi, although I did not test SWA with those detectors you mentioned, I think SWA training should work with them. Please see [the instructions](https://github.com/hyz-xmaster/swa_object_detection#instructions) about how to apply SWA training to them.

**Comment by pu2is** [comment]
cool thanks a lot!!
