### ISSUE TITLE
problem in get_swa_model.py

### ISSUE THREAD

**Issue by lkct** [hyz-xmaster/swa_object_detection#11]
Hi, @hyz-xmaster . Thanks for releasing the code.

When using your utils to get the avg model [get_swa_model.py](https://github.com/hyz-xmaster/swa_object_detection/blob/2feb86790a41f91c3167fb282ba47dc295c65658/swa/get_swa_model.py), I've got a problem. For example, if I want to avg chkpts of 13-24 epochs, I would intuitively pass starting=13 and ending=24 in args. However, the code actually gave me the avg of 13-23, because of this line:
https://github.com/hyz-xmaster/swa_object_detection/blob/2feb86790a41f91c3167fb282ba47dc295c65658/swa/get_swa_model.py#L28

I think it would be better to use `ending_id + 1` instead of `ending_id` for easier understanding.

**Comment by hyz-xmaster** [comment]
Hi @lkct , thanks for reporting this. Corrected.
