### ISSUE TITLE
how to use of swa repo correctly

### ISSUE THREAD

**Issue by yustaub** [hyz-xmaster/swa_object_detection#12]
Hello, sir. This is a nice work! I want to use this repo to improve my detection performance, but there are some question about using this repo.
I have trained my detection model in mmdetection, and get the epoch_12.pth normally, and follow the Only-SWA mode make the config, 
![image](https://user-images.githubusercontent.com/40256410/112707520-0f498c80-8ee7-11eb-811d-8cc59291503c.png)
after training, there are 24 models in my work_dir:

![image](https://user-images.githubusercontent.com/40256410/112707557-46b83900-8ee7-11eb-8046-74576ca91e70.png)
I use swa/get_swa_model.py which use swa_epoch_1.pth to swa_epoch_12.pth to produce swa_1-12.pth, and I use this model to test, the final score decrease a little, is there some problem when I use swa? Very confused, and very appreciate for your reply!!

**Comment by hyz-xmaster** [comment]
Hi @yustaub, the get_swa_model.py is just a helper function and has been updated very recently according to #11 . In general, you do not need use this function. 

Taking a closer look at your log file, you should find one best swa model, which may be swa_model_12.pth or swa_model_xx.pth, and you should use this one as your final model.  

There is also one concern about BN weights. In this repo, the BN layers are assumed to be frozen. If you did not freeze the BN layers in the backbone during training,  eg you adopt Synchronized BN in the backbone, you may need to update BN statistics after the swa averaging by conducting a new forward pass.   [This post](https://zhuanlan.zhihu.com/p/122504469) may be helpful.

**Comment by yustaub** [comment]
I use the swa_model_12.pth and get the same result as what I do before, and I don't use Synchronized BN, I use the defualt cascade_r50 config. @hyz-xmaster

**Comment by hyz-xmaster** [comment]
So your problem is solved or you mean there is no performance boost in your case?

**Comment by yustaub** [comment]
yes, just keep almost the same performance with original epoch_12.pth. @hyz-xmaster

**Comment by hyz-xmaster** [comment]
What are the performances of swa_model_2.pth to swa_model_11.pth? The best model is not necessarily the swa_model_12.pth. 

Also, you can try setting lr=0.02 in swa_optimizer, as I noticed that the initial learning rate used in training cascade_rcnn is 0.02.

**Comment by yustaub** [comment]
ok, I will try it. Thank you!!
