### ISSUE TITLE
Performance with other optimizer, such as Adam, AdamW

### ISSUE THREAD

**Issue by xinge008** [hyz-xmaster/swa_object_detection#14]
Hi, thanks for your nice work.

I am wondering the performance of SWA with other optimizers, such as Adam, Adamw; 
Can it achieve consistent performance gain?

If the original network is trained with Adam or Adamw, can SWA (with SGD) improve its performance?

Thanks very much.

**Comment by hyz-xmaster** [comment]
You are trying to play SWA with Transformer based detectors?
I have only tried training SWA + Swin transformer based detector which is optimized by AdamW, and got 0.6 AP improvement (52.8 -> 53.4) on COCO val. I think SWA + SGD could also achieve some gain, but I did not verify this.

**Comment by xinge008** [comment]
Thanks for your quick reply.

In your SWA+Swin experiment, both original network and SWA are trained with AdamW?

Did you try training original network and SWA with different optimizers?

**Comment by hyz-xmaster** [comment]
> In your SWA+Swin experiment, both original network and SWA are trained with AdamW?

Yes.

> Did you try training original network and SWA with different optimizers?

No. But I think even if the SWA training is performed  with different optimizers, some performance gain can still be achieved, because those optimizers are basically similar.

**Comment by xinge008** [comment]
OK, thanks very much
