### ISSUE TITLE
what's the difference between swa_epoch_xx.pth and swa_model_xx.pth?

### ISSUE THREAD

**Issue by HuXinzhi1004** [hyz-xmaster/swa_object_detection#16]
Hello sir! I appreciate your wonderful work which helps a lot. But there's a question I can't figure out.

When I run Two-pahse mode, after I got 12 traditional checkpoints, I can get 2 checkpoints after each epoch. I wonder the difference between them, and which one should I use?

epoch_1.pth to epoch_12.pth is traditional checkpoints 
![image](https://user-images.githubusercontent.com/75877054/141679940-9cd866f3-4070-4a82-92f1-9a9f1572a6f4.png)

swa_epoch_xx.pth and swa_model_xx.pth are the checkpoints after swa training
![image](https://user-images.githubusercontent.com/75877054/141680213-8a15d8f9-faf4-44f6-a6aa-2d078a13df55.png)
![image](https://user-images.githubusercontent.com/75877054/141680229-a0b7a2c4-25bc-4022-85f6-eff4217c62e8.png)

**Comment by hyz-xmaster** [comment]
> I wonder the difference between them, and which one should I use?

Hi, @HuXinzhi1004, swa_epoch_xx.pth is like the traditional epoch and is the checkpoint of each swa training epoch; swa_model_xx.pth is the average model of checkpoints from swa_epoch_01 to swa_epoch_xx. So generally you should use swa_model_xx.pth.

**Comment by HuXinzhi1004** [comment]
get it, thank you!
