### ISSUE TITLE
Can I use  dist_train.sh to train the original model?

### ISSUE THREAD

**Issue by yushanshan05** [hyz-xmaster/swa_object_detection#4]
I think I should train the original model at first, then start to train the  extra checkpoints.

But  the  scripts as follows in README.md don't include the script of training the original model.
I think the first script  as follows  only trains the  extra checkpoints of 12/24 epochs. And  the second script  as follows  averages these 12/24 checkpoints for final detection model.
(1)./tools/dist_train.sh configs/swa/swa_mask_rcnn_r101_fpn_2x_coco.py
(2)./swa/get_swa_model.py work_dirs/swa_mask_rcnn_r101_fpn_2x_coco 1 12 --save_dir work_dirs/swa_mask_rcnn

Maybe  I can use this  script as follow to  train the original model. 
./tools/dist_train.sh configs/mask_rcnn/mask_rcnn_r101_fpn_2x_coco.py work_dir=mymodel
 Then I  can use this  script as follow  to train the  extra checkpoints. And I must set work_dir to the path where saves the  original model. 
./tools/dist_train.sh configs/swa/swa_mask_rcnn_r101_fpn_2x_coco.py work_dir=mymodel

Am I right?
Thanks very much!

**Comment by hyz-xmaster** [comment]
Yes, most of your understanding is correct. When you train extra epochs for SWA, you need to specify the starting model using `--cfg-options load_from` argument. `work_dir` only specifies where you are going to save the checkpoints. One example is:
`./tools/dist_train.sh configs/swa/swa_mask_rcnn_r101_fpn_2x_coco.py 8 --cfg-options load_from=mymodel/epoch_x.pth work_dir=xxxxxx`

I think you can read [instructions about how to use MMDetection](https://github.com/hyz-xmaster/swa_object_detection/blob/master/docs/1_exist_data_model.md#train-predefined-models-on-standard-datasets) to get more information.

**Comment by yushanshan05** [comment]
Thanks！
I ignore the  load_from.
